import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yeison Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Ir a <a href="https://personal-yeison.herokuapp.com/">About</a>
        </h1>
      </main>
    </div>
  );
}
